services:
  app:
    image: lasertag-backend
    ports:
      - ${PORT}:${PORT}
    restart: always
    depends_on:
      - redis
    volumes:
      - log-data:/app/logs
    env_file:
      - .env
    
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

volumes:
  log-data:
    name: log-data
    driver: local