services:
  app:
    image: lasertag-backend
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    depends_on:
      - mongodb
      - redis
    volumes:
      - log-data:/app/logs
    env_file:
      - .env

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-data:/data/db
    
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - 6379:6379
    restart: always

volumes:
  mongo-data:
    name: lasertag-data
    driver: local
  log-data:
    name: log-data
    driver: local