name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Changes
        run: git pull origin main
        working-directory: /home/gravitas/lasertag-gravitas-csi

      - name: Build and Deploy
        run: docker compose -f compose-prod.yaml up --build -d
        working-directory: /home/gravitas/lasertag-gravitas-csi
